#Autor: Tiago André Lopes
#Email: tiago.lopes@aluno.faculdadeimpacta.com.br
#Disciplina: Infrastructure and Cloud Computing
#Atividade 01: Subir uma máquina virtual, usando Vagrant, com MySQL instalado e que esteja acessível no
#host da máquina na porta 3306.
#Enviar a URL Github do código.

#Instação do MySQL com carga - parte 2.
$script_mysql = <<-SCRIPT
  apt-get update && \
  apt-get install -y mysql-server-5.7 && \
  mysql < /vagrant/mysql/script/user.sql && \
  mysql < /vagrant/mysql/script/schema.sql && \
  mysql < /vagrant/mysql/script/data.sql && \
  cat /vagrant/mysql/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf && \
  service mysql restart
SCRIPT

#Maquina Virtual Vagrant Pai
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  #Maquina Virtual Vagrant Filha com capacidade alocada.
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
	vb.cpus = 1
  end
  
  #Instação do MySQL - parte 1 no Localhost da máquina na porta 3306
  config.vm.define "mysqlserver2" do |mysqlserver2|
    mysqlserver2.vm.network "private_network", ip: "10.80.4.10"
    mysqlserver2.vm.network "forwarded_port", guest: 8080, host: 3306

    mysqlserver2.vm.provider "virtualbox" do |vb|
      vb.name = "mysqlserver2"
    end

    mysqlserver2.vm.provision "shell", inline: $script_mysql
  end
end