#Autor: Tiago André Lopes
#Email: tiago.lopes@aluno.faculdadeimpacta.com.br
#Disciplina: Infrastructure and Cloud Computing
#Aula 04: Acesso externo ao cluster do nginx

apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-pod
spec:
  selector:
    app: nginx-pod
  #type: CluesterIP
  #type: NodePort
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 80